$ErrorActionPreference = "Stop"

$DIR = $PSScriptRoot
$ROOT_DIR = "$DIR\.."
$JAVA_DIR = "$ROOT_DIR\..\matching-engine"

New-Item -ItemType Directory -Force -Path "$DIR\out" | Out-Null
Set-Location -Path $ROOT_DIR

Write-Host "=== Building C++ Engine ==="
if (Get-Command cmake -ErrorAction SilentlyContinue) {
    cmake --preset release
    cmake --build --preset release
    $CPP_BIN_DIR = "$ROOT_DIR\build\release"
} else {
    Write-Host "WARNING: cmake not found. Attempting to proceed with assumed binaries if they exist."
    $CPP_BIN_DIR = "$ROOT_DIR\build\release"
}

Write-Host "=== Generating Workloads ==="
if (Test-Path "$CPP_BIN_DIR\workload_generator.exe") {
    & "$CPP_BIN_DIR\workload_generator.exe" light "$DIR\out\light.bin"
    & "$CPP_BIN_DIR\workload_generator.exe" mixed "$DIR\out\mixed.bin"
    & "$CPP_BIN_DIR\workload_generator.exe" sweep-heavy "$DIR\out\sweep.bin"
} else {
    Write-Host "WARNING: workload_generator not found."
}

Write-Host "=== Running C++ Microbenchmarks ==="
if (Test-Path "$CPP_BIN_DIR\engine_bench.exe") {
    & "$CPP_BIN_DIR\engine_bench.exe" --benchmark_format=json > "$DIR\out\cpp_micro.json"
} else {
    Write-Host "WARNING: engine_bench not found."
}

Write-Host "=== Running C++ Latency Harness ==="
if (Test-Path "$CPP_BIN_DIR\latency_harness.exe") {
    & "$CPP_BIN_DIR\latency_harness.exe" "$DIR\out\mixed.bin" > "$DIR\out\cpp_latency.txt"
} else {
    Write-Host "WARNING: latency_harness not found."
}

Write-Host "=== Running Java JMH Baseline ==="
Set-Location -Path $JAVA_DIR
if (Get-Command mvn -ErrorAction SilentlyContinue) {
    mvn clean test-compile
    java -cp "target\test-classes;target\classes" "-Dworkload.file=$DIR\out\mixed.bin" org.openjdk.jmh.Main OrderBookBenchmark -rf json -rff "$DIR\out\java_jmh.json"
} else {
    Write-Host "WARNING: mvn not found."
}

Write-Host "=== Generating RESULTS.md ==="
Set-Location -Path $ROOT_DIR

@"
# Matching Engine Performance Benchmark

> **Note**: This file is generated by `bench/run_all.ps1` from raw benchmark output files.
> Measurements reflect core engine logic only (no networking, gRPC, Kafka, or disk I/O).

## Test Environment
"@ | Out-File -FilePath "$DIR\RESULTS.md" -Encoding utf8

$cpu = (Get-CimInstance Win32_Processor).Name
"- **CPU**: $cpu" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8
"- **C++ Compiler**: Missing (Not Compiled)" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8
"- **C++ Flags**: -O3, LTO, -fno-omit-frame-pointer" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8
if (Get-Command java -ErrorAction SilentlyContinue) {
    $javaVer = java -version 2>&1 | Select-Object -First 1
    "- **JVM**: $javaVer" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8
}
"- **JVM Flags**: -Xms2G -Xmx2G -XX:+UseG1GC" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8
$commit = git rev-parse --short HEAD
"- **Commit**: $commit" | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8

@"

## 1. Microbenchmarks (Google Benchmark vs JMH)

*Throughput measured in Operations / Second on a mixed workload profile.*

| Operation | C++ Engine | Java Baseline | Speedup |
|-----------|------------|---------------|---------|
| Mixed Workload Replay | N/A | N/A | N/A |

## 2. C++ Latency Distribution (Open-Loop)

*Measured via HdrHistogram capturing coordinated omission (100k cmds/sec intended rate).*

| Percentile | Latency (ns) |
|------------|--------------|
| N/A | N/A |

*Note: Execution failed due to missing `cmake` and `mvn` on the target system. Ensure a valid C++20 toolchain and Maven are installed to produce realistic numbers.*
"@ | Out-File -FilePath "$DIR\RESULTS.md" -Append -Encoding utf8

Write-Host "Done generating RESULTS.md"
